#!perl

# DATE
# VERSION

use 5.010001;
use strict;
use warnings;

use Getopt::Long;

my %Opts = (
    # highlight => 1,
    reverse => 0,
    parser => 'Date::Extract',
);
my $Parser;
my $Code_Parse;

sub parse_cmdline {
    my $res = GetOptions(
        'reverse|v'        => \$Opts{reverse},
        'parser=s'         => \$Opts{parser},
        'version|V'        => sub {
            no warnings 'once';
            say "grepdate version ", ($main::VERSION // 'dev');
            exit 0;
        },
        'help|h'           => sub {
            print <<USAGE;
Usage:
  grepdate [OPTIONS]... [FILES]...
  grepdate --help|-h
  grepdate --version|-V
Options:
  --reverse, -v
  --parser=s
For more details, see the manpage/documentation.
USAGE
            exit 0;
        },
    );
    exit 99 if !$res;

    if ($Opts{parser} eq 'Date::Extract') {
        require Date::Extract;
        $Parser = Date::Extract->new(format => 'combined');
        $Code_Parse = sub { $Parser->extract($_[0]) };
    } elsif ($Opts{parser} eq 'Date::Extract::ID') {
        require Date::Extract::ID;
        $Parser = Date::Extract::ID->new(format => 'combined');
        $Code_Parse = sub { $Parser->extract($_[0]) };
    } elsif ($Opts{parser} eq 'DateTime::Format::Alami::EN') {
        require DateTime::Format::Alami::EN;
        $Parser = DateTime::Format::Alami::EN->new;
        $Code_Parse = sub {
            my $h;
            eval { $h = $Parser->parse_datetime($_[0], {format=>'combined'}) };
            return undef if $@;
            $h;
        };
    } elsif ($Opts{parser} eq 'DateTime::Format::Alami::ID') {
        require DateTime::Format::Alami::ID;
        $Parser = DateTime::Format::Alami::ID->new;
        $Code_Parse = sub {
            my $h;
            eval { $h = $Parser->parse_datetime($_[0], {format=>'combined'}) };
            return undef if $@;
            $h;
        };
    }
}

sub run {
    require Date::Extract;

    my $parser = Date::Extract->new(
        format => "combined",
        returns => "first",
    );
    while (<>) {
        my $found;
        my $h = $Code_Parse->($_);
        if ($h) {
            $found++;
            s/(\Q$h->{verbatim}\E)/\e[1;31m$1\e[0m/;
        }
        if ($Opts{reverse}) {
            next if $found;
        } else {
            next unless $found;
        }
        print;
    }
}

# MAIN

parse_cmdline();
run();

1;
# ABSTRACT: Grep date in text
# PODNAME: grepdate

=head1 SYNOPSIS

 grepdate [OPTION]... [FILES]...


=head1 DESCRIPTION


=head1 OPTIONS

=over

=item * --reverse, -v

=item * --parser=s (default: Date::Extract)

Choose either L<Date::Extract>, L<Date::Extract::ID>,
L<DateTime::Format::Alami::EN>, L<DateTime::Format::Alami::ID>.

=back

=head1 EXIT CODES

0 on success.

255 on I/O error.

99 on command-line options error.


=head1 FAQ

=cut
